config/routes.rb
Blogs::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show] do
    resources :subdomains
  end
  match '/' => 'sites#show', constraints: ->(r) { r.subdomain.present? && r.subdomain != 'www' }
  root :to => "home#index"
  # resources :articles
  # resources :blogs
  # match '', to:'blogs#show', constraints: ->(r) { r.subdomain.present? && r.subdomain != 'www' }
  # root to: "blogs#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :blog
  attr_accessible :name, :content, :published_at
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name, :subdomain
  has_many :articles
end

app/models/site.rb
class Site < Subdomain
end

app/models/subdomain.rb
class Subdomain < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  validates_uniqueness_of :name, case_sensitive: false
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subdomains, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  validates_uniqueness_of :name, case_sensitive: false
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :limit_subdomain_access

  private

  def set_blog
    @blog = Blog.find_by_subdomain!(request.subdomain)
  end

  def limit_subdomain_access
    if request.subdomain.present?
      redirect_to root_url(subdomain: false)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :set_blog
  # GET /articles
  # GET /articles.json
  def index
    @articles = @blog.articles

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = @blog.articles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = @blog.articles.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = @blog.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = @blog.articles.build(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = @blog.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = @blog.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :set_blog, only: [:show]
  def index
    @blogs = Blog.all
  end
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  skip_before_filter :limit_subdomain_access

  def show
    @site = Site.find_by_name!(request.subdomain)
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url(subdomain: false), notice: "Site #{request.subdomain} was not found!"
  end
end

app/controllers/subdomains_controller.rb
class SubdomainsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :set_user
  before_filter :set_subdomain
  respond_to :html

  # GET /subdomains
  # GET /subdomains.json
  def index
    @subdomains = Subdomain.all
    respond_with @subdomains
  end

  # GET /subdomains/1
  # GET /subdomains/1.json
  def show
    respond_with @subdomain
  end

  # GET /subdomains/new
  # GET /subdomains/new.json
  def new
    respond_with @subdomain
  end

  # GET /subdomains/1/edit
  def edit
    respond_with @subdomain
  end

  # POST /subdomains
  # POST /subdomains.json
  def create
    @subdomain = @user.subdomains.build(params[:subdomain])
    if @subdomain.save
      redirect_to @user, notice: "Successfully created subdomain."
    end
  end

  # PUT /subdomains/1
  # PUT /subdomains/1.json
  def update
    if @subdomain.update_attributes(params[:subdomain])
      flash[:notice] = "Successfully updated subdomain."
    end
    respond_with([@user, @subdomain])
  end

  # DELETE /subdomains/1
  # DELETE /subdomains/1.json
  def destroy
    @subdomain.destroy
    redirect_to @user, notice: "Successfully destroyed subdomain."
  end

  private

  def set_subdomain
    @subdomain = params[:id] ? @user.subdomains.find(params[:id]) : @user.subdomains.build
  end

  def set_user
    if params[:user_id]
      @user = User.find(params[:user_id])
    else
      @user = @subdomain.user
    end
    unless current_user == @user
      redirect_to @user, :alert => "Are you logged in properly? You are not allowed to create or change someone else's subdomain."
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/subdomains_helper.rb
module SubdomainsHelper
end

app/views/articles/_article.html.erb
<h2><%= link_to article.name, article %></h2>
<%= article.content %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :blog %><br />
    <%= f.text_field :blog %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Blog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.body %></td>
    <td><%= article.blog %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @article.name %></h2>

<%= @article.content %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<p><%= link_to "View List of Users", users_path %></p>

<%- @blogs.each do |blog| -%>
  <p><%= link_to blog.name, root_url(subdomain: blog.subdomain) %></p>
<%- end unless @blogs.blank? -%>

app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1>
<%= render @blog.articles -%>

app/views/home/index.html.erb
<h1>Rails3-Subdomain-Devise</h1>
<p><%= link_to "View List of Users", users_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="hmenu">
    <%= link_to 'Home', root_url(subdomain: false) %>
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
  </ul>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/sites/show.html.erb
<h1>Site: <%= @site.name %></h1>
<p>Belongs to: <%= link_to @site.user.name, user_url(@site.user, subdomain: false) %></p>
<p><%= link_to 'Home', root_url(subdomain: false) %></p>

app/views/subdomains/_form.html.erb
<% if @subdomain.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@subdomain.errors.count, "error") %> prohibited this subdomain from being saved:</h2>

    <ul>
    <% @subdomain.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= fields_for @subdomain do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.hidden_field(:user_id, value: @subdomain.user_id) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subdomains/edit.html.erb
<h1>Editing subdomain</h1>
<%= form_for [@user, @subdomain] do |f| %>
  <%= render 'form' %>
<%- end -%>
<%= link_to 'Show', [@user, @subdomain] %> |
<%= link_to @subdomain.user.name, user_url(@subdomain.user) %>

app/views/subdomains/index.html.erb
<h1>Listing subdomains</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subdomains.each do |subdomain| %>
  <tr>
    <td><%= link_to subdomain.name, subdomain %></td>
    <td>(belongs to <%= link_to subdomain.user.name, user_url(subdomain.user) %>)</td>
    <td><%= link_to 'Edit', edit_subdomain_url(subdomain) %></td>
    <td><%= link_to 'Destroy', subdomain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subdomain', new_subdomain_url %>

app/views/subdomains/new.html.erb
<h1>New subdomain</h1>
<%= form_for([@user, @subdomain]) do |f| %>
  <%= render 'form' %>
<% end %>
<%= link_to @user.name, user_url(@user) %>

app/views/subdomains/show.html.erb
<h1><%= @subdomain.name %></h1>
<p>Belongs to: <%= link_to @subdomain.user.name, user_url(@subdomain.user) %></p>
<%= link_to 'Edit', edit_user_subdomain_url(@user, @subdomain) %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Email: <%= @user.email %></p>
<p><%= link_to 'Edit', edit_user_registration_path %></p>
<p><%= link_to 'List of Users', users_path %></p>
<h3><%= @user.name %>'s Subdomains</h3>
<table>
<% @user.subdomains.each do |subdomain| %>
  <tr>
    <td><%= link_to subdomain.name, [@user, subdomain] %></td>
    <td><%= link_to 'Edit', edit_user_subdomain_url(@user, subdomain) %></td>
    <td><%= link_to 'Destroy', [@user, subdomain], :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to "Visit #{root_url(subdomain: subdomain.name)}", root_url(subdomain: subdomain.name) %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to "Add New Subdomain", new_user_subdomain_url(@user) %>